package com.welab.bill.pojo;

import java.util.Date;

public class Tbbill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.billid
     *
     * @mbg.generated
     */
    private String billid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.billdate
     *
     * @mbg.generated
     */
    private String billdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.billinfo
     *
     * @mbg.generated
     */
    private String billinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.billamount
     *
     * @mbg.generated
     */
    private Double billamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.username
     *
     * @mbg.generated
     */
    private Integer username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbbill.classa
     *
     * @mbg.generated
     */
    private String classa;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.billid
     *
     * @return the value of tbbill.billid
     *
     * @mbg.generated
     */
    public String getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.billid
     *
     * @param billid the value for tbbill.billid
     *
     * @mbg.generated
     */
    public void setBillid(String billid) {
        this.billid = billid == null ? null : billid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.billdate
     *
     * @return the value of tbbill.billdate
     *
     * @mbg.generated
     */
    public String getBilldate() {
        return billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.billdate
     *
     * @param billdate the value for tbbill.billdate
     *
     * @mbg.generated
     */
    public void setBilldate(String billdate) {
        this.billdate = billdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.billinfo
     *
     * @return the value of tbbill.billinfo
     *
     * @mbg.generated
     */
    public String getBillinfo() {
        return billinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.billinfo
     *
     * @param billinfo the value for tbbill.billinfo
     *
     * @mbg.generated
     */
    public void setBillinfo(String billinfo) {
        this.billinfo = billinfo == null ? null : billinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.billamount
     *
     * @return the value of tbbill.billamount
     *
     * @mbg.generated
     */
    public Double getBillamount() {
        return billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.billamount
     *
     * @param billamount the value for tbbill.billamount
     *
     * @mbg.generated
     */
    public void setBillamount(Double billamount) {
        this.billamount = billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.typeid
     *
     * @return the value of tbbill.typeid
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.typeid
     *
     * @param typeid the value for tbbill.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.username
     *
     * @return the value of tbbill.username
     *
     * @mbg.generated
     */
    public Integer getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.username
     *
     * @param username the value for tbbill.username
     *
     * @mbg.generated
     */
    public void setUsername(Integer username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbbill.classa
     *
     * @return the value of tbbill.classa
     *
     * @mbg.generated
     */
    public String getClassa() {
        return classa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbbill.classa
     *
     * @param classa the value for tbbill.classa
     *
     * @mbg.generated
     */
    public void setClassa(String classa) {
        this.classa = classa == null ? null : classa.trim();
    }
}