package com.welab.bill.pojo;

public class Tbdeposittype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeposittype.depositid
     *
     * @mbg.generated
     */
    private String depositid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeposittype.typename
     *
     * @mbg.generated
     */
    private String typename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdeposittype.mark
     *
     * @mbg.generated
     */
    private Integer mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeposittype.depositid
     *
     * @return the value of tbdeposittype.depositid
     *
     * @mbg.generated
     */
    public String getDepositid() {
        return depositid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeposittype.depositid
     *
     * @param depositid the value for tbdeposittype.depositid
     *
     * @mbg.generated
     */
    public void setDepositid(String depositid) {
        this.depositid = depositid == null ? null : depositid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeposittype.typename
     *
     * @return the value of tbdeposittype.typename
     *
     * @mbg.generated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeposittype.typename
     *
     * @param typename the value for tbdeposittype.typename
     *
     * @mbg.generated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdeposittype.mark
     *
     * @return the value of tbdeposittype.mark
     *
     * @mbg.generated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdeposittype.mark
     *
     * @param mark the value for tbdeposittype.mark
     *
     * @mbg.generated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }
}