package com.welab.bill.pojo;

public class Tbdrawtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdrawtype.drawid
     *
     * @mbg.generated
     */
    private String drawid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdrawtype.classa
     *
     * @mbg.generated
     */
    private String classa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdrawtype.classb
     *
     * @mbg.generated
     */
    private String classb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbdrawtype.mark
     *
     * @mbg.generated
     */
    private Integer mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdrawtype.drawid
     *
     * @return the value of tbdrawtype.drawid
     *
     * @mbg.generated
     */
    public String getDrawid() {
        return drawid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdrawtype.drawid
     *
     * @param drawid the value for tbdrawtype.drawid
     *
     * @mbg.generated
     */
    public void setDrawid(String drawid) {
        this.drawid = drawid == null ? null : drawid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdrawtype.classa
     *
     * @return the value of tbdrawtype.classa
     *
     * @mbg.generated
     */
    public String getClassa() {
        return classa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdrawtype.classa
     *
     * @param classa the value for tbdrawtype.classa
     *
     * @mbg.generated
     */
    public void setClassa(String classa) {
        this.classa = classa == null ? null : classa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdrawtype.classb
     *
     * @return the value of tbdrawtype.classb
     *
     * @mbg.generated
     */
    public String getClassb() {
        return classb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdrawtype.classb
     *
     * @param classb the value for tbdrawtype.classb
     *
     * @mbg.generated
     */
    public void setClassb(String classb) {
        this.classb = classb == null ? null : classb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbdrawtype.mark
     *
     * @return the value of tbdrawtype.mark
     *
     * @mbg.generated
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbdrawtype.mark
     *
     * @param mark the value for tbdrawtype.mark
     *
     * @mbg.generated
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }
}