package com.welab.bill.pojo;

public class Tbtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbtype.typeid
     *
     * @mbg.generated
     */
    private Integer typeid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbtype.typename
     *
     * @mbg.generated
     */
    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbtype.typeid
     *
     * @return the value of tbtype.typeid
     *
     * @mbg.generated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbtype.typeid
     *
     * @param typeid the value for tbtype.typeid
     *
     * @mbg.generated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbtype.typename
     *
     * @return the value of tbtype.typename
     *
     * @mbg.generated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbtype.typename
     *
     * @param typename the value for tbtype.typename
     *
     * @mbg.generated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }
}