package com.welab.bill.pojo;

import java.util.Date;

public class Tbuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.username
     *
     * @mbg.generated
     */
    private Integer username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.birthday
     *
     * @mbg.generated
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.userinfo
     *
     * @mbg.generated
     */
    private String userinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbuser.useramount
     *
     * @mbg.generated
     */
    private Double useramount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.username
     *
     * @return the value of tbuser.username
     *
     * @mbg.generated
     */
    public Integer getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.username
     *
     * @param username the value for tbuser.username
     *
     * @mbg.generated
     */
    public void setUsername(Integer username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.password
     *
     * @return the value of tbuser.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.password
     *
     * @param password the value for tbuser.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.name
     *
     * @return the value of tbuser.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.name
     *
     * @param name the value for tbuser.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.birthday
     *
     * @return the value of tbuser.birthday
     *
     * @mbg.generated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.birthday
     *
     * @param birthday the value for tbuser.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.sex
     *
     * @return the value of tbuser.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.sex
     *
     * @param sex the value for tbuser.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.userinfo
     *
     * @return the value of tbuser.userinfo
     *
     * @mbg.generated
     */
    public String getUserinfo() {
        return userinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.userinfo
     *
     * @param userinfo the value for tbuser.userinfo
     *
     * @mbg.generated
     */
    public void setUserinfo(String userinfo) {
        this.userinfo = userinfo == null ? null : userinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbuser.useramount
     *
     * @return the value of tbuser.useramount
     *
     * @mbg.generated
     */
    public Double getUseramount() {
        return useramount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbuser.useramount
     *
     * @param useramount the value for tbuser.useramount
     *
     * @mbg.generated
     */
    public void setUseramount(Double useramount) {
        this.useramount = useramount;
    }
}