package com.welab.bill.dao;

import com.welab.bill.pojo.MyJss;
import com.welab.bill.pojo.Tbbill;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface TbbillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("billid") String billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbill
     *
     * @mbg.generated
     */
    int insert(Tbbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbill
     *
     * @mbg.generated
     */
    int insertSelective(Tbbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbill
     *
     * @mbg.generated
     */
    Tbbill selectByPrimaryKey(@Param("billid")String billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tbbill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbbill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tbbill record);

    /**
     *
     * @param start
     * @param end
     * @return
     */
    List<Tbbill> selectByBillDate(@Param("start") Date start,@Param("end") Date end);

    /**
     *
     * @return
     */
    List<Tbbill> findAll();

    /**
     *查询某人某个时间段内每天的收支情况
     *
     * @param username
     * @param start
     * @param end
     * @return
     */
    List<MyJss> mrmgsjdmtszqk(@Param("username") Integer username,@Param("start") Date start,@Param("end") Date end);

}