package com.welab.bill.dao;

import com.welab.bill.pojo.Tbdeposittype;

import java.util.List;

public interface TbdeposittypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeposittype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String depositid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeposittype
     *
     * @mbg.generated
     */
    int insert(Tbdeposittype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeposittype
     *
     * @mbg.generated
     */
    int insertSelective(Tbdeposittype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeposittype
     *
     * @mbg.generated
     */
    Tbdeposittype selectByPrimaryKey(String depositid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeposittype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tbdeposittype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdeposittype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tbdeposittype record);


    List<Tbdeposittype> getAll();
}