package com.welab.bill.dao;

import com.welab.bill.pojo.Tbdrawtype;

public interface TbdrawtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdrawtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String drawid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdrawtype
     *
     * @mbg.generated
     */
    int insert(Tbdrawtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdrawtype
     *
     * @mbg.generated
     */
    int insertSelective(Tbdrawtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdrawtype
     *
     * @mbg.generated
     */
    Tbdrawtype selectByPrimaryKey(String drawid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdrawtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tbdrawtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbdrawtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tbdrawtype record);
}