package com.welab.bill.dao;

import com.welab.bill.pojo.Tbtype;

public interface TbtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtype
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtype
     *
     * @mbg.generated
     */
    int insert(Tbtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtype
     *
     * @mbg.generated
     */
    int insertSelective(Tbtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtype
     *
     * @mbg.generated
     */
    Tbtype selectByPrimaryKey(Integer typeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tbtype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbtype
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tbtype record);
}