package com.welab.bill.dao;

import com.welab.bill.pojo.Tbuser;

public interface TbuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated
     */
    int insert(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated
     */
    int insertSelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated
     */
    Tbuser selectByPrimaryKey(Integer username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tbuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbuser
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tbuser record);
}